@SemanticKernelRag.Api_HostAddress = http://localhost:5137

POST {{SemanticKernelRag.Api_HostAddress}}/api/chat
Accept: application/json

{
    "message": "Meu nome é Wellerson. Trabalho como desenvolvedor de software."
}

###
